### ISSUE TITLE
Milestone 4 Tasks

### ISSUE THREAD

**Issue by bfrizzell01** [UBC-MDS/mushroom_classifier#30]
- [x] Create `Makefile` to run scripts (and update `README`): Benjamin
- [x] Abstract script code to functions and implement testing: Mason and Essie
- [x] Address 4+ peer review changes in `CHANGELOG.md` file: Krabs, Benjamin
- [x] Code/Pull Request Review: Benjamin
